function [output_word] = CRC16_FCS(baseCRCgen, input_word)
%CRC16 function computes CRC field. It is the first complement of the
%remainder generated by the modulo 2 division of the protected data fields
%by the polynomial x^16+x^12+x^5+1

% Author: Jiri Milos, DREL FEEC BUT, 05/2015

% initialize CRC registers to ones
set(baseCRCgen,'InitialConditions', [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1])

for i = 1:length(input_word)
    input_bit = input_word(i);
    tmp_outputCRC = step(baseCRCgen, input_bit);
    
    % set output as the 'InitialConditions'
    release(baseCRCgen)
    set(baseCRCgen, 'InitialConditions', tmp_outputCRC(1:16))
end

output_word = single(~tmp_outputCRC(1:16));
end

